listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

stats {
    network         0;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    3;
        hls_window      10;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    # push rtmp://a.rtmp.youtube.com/live2/YOUR_YOUTUBE_STREAM_KEY;
    # push rtmp://rtmp-api.facebook.com:80/rtmp/YOUR_FACEBOOK_STREAM_KEY;
    # push rtmp://live.twitch.tv/app/YOUR_TWITCH_STREAM_KEY;
    # push rtmp://push.tiktoklive.com/live?stream_key=YOUR_TIKTOK_STREAM_KEY;
}
